language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t byvenom/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true byvenom/react-test-app npm run test

after_success:
  - docker build -t byvenom/docker-frontend ./forntend
  - docker build -t byvenom/docker-backend ./backend
  - docker build -t byvenom/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push byvenom/docker-frontend
  - docker push byvenom/docker-backend
  - docker push byvenom/docker-nginx